# Generated by Django 5.2.4 on 2025-07-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeepurchase',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
