# Generated by Django 5.2.4 on 2025-07-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0002_coffeepurchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeepurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
