# Generated by Django 5.2.4 on 2025-07-23 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0003_coffeepurchase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeepurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
