# Generated by Django 5.2.4 on 2025-07-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0004_alter_coffeepurchase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
