# Generated by Django 5.2.4 on 2025-07-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0005_alter_creator_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeepurchase',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
