# Generated by Django 5.2.4 on 2025-07-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0006_alter_coffeepurchase_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
