# Generated by Django 5.2.4 on 2025-08-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0007_creator_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeepurchase',
            name='coffee_qty',
            field=models.IntegerField(default=1),
        ),
    ]
