# Generated by Django 5.2.4 on 2025-08-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0008_coffeepurchase_coffee_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeepurchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
