# Generated by Django 5.2.4 on 2025-08-04 08:36

import coffeez.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0009_alter_coffeepurchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='creator_pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), coffeez.validators.validate_file_size]),
        ),
    ]
