# Generated by Django 5.2.4 on 2025-08-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0010_alter_creator_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
