# Generated by Django 5.2.4 on 2025-08-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0011_creator_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeepurchase',
            name='buyer_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
