# Generated by Django 5.2.4 on 2025-08-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0012_coffeepurchase_buyer_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
