# Generated by Django 5.2.4 on 2025-08-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0014_email_verification_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationcode',
            new_name='coffeez_ema_user_id_03cf4b_idx',
            old_name='coffeez_ema_user_code_used_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationcode',
            new_name='coffeez_ema_expires_033326_idx',
            old_name='coffeez_ema_expires_idx',
        ),
    ]
