# Generated by Django 5.2.4 on 2025-08-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0015_rename_coffeez_ema_user_code_used_idx_coffeez_ema_user_id_03cf4b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeepurchase',
            name='creator_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
