# Generated by Django 5.2.4 on 2025-08-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0016_coffeepurchase_creator_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
