# Generated by Django 5.2.4 on 2025-08-21 19:58

import coffeez.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0017_creator_deactivated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[coffeez.validators.validate_username]),
        ),
    ]
