# Generated by Django 5.2.4 on 2025-08-23 14:50

from django.db import migrations


def drop_allauth_tables(apps, schema_editor):
    """
    Drop allauth-related tables if they exist
    """
    from django.db import connection
    
    allauth_tables = [
        'django_site',
        'socialaccount_socialaccount',
        'socialaccount_socialtoken',
        'socialaccount_socialapp',
        'socialaccount_socialapp_sites',
        'account_emailaddress',
        'account_emailconfirmation',
    ]
    
    with connection.cursor() as cursor:
        for table in allauth_tables:
            try:
                cursor.execute(f"DROP TABLE IF EXISTS {table}")
            except Exception:
                # Ignore errors if table doesn't exist
                pass


def reverse_drop_allauth_tables(apps, schema_editor):
    """
    This is a non-reversible migration
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('coffeez', '0018_alter_creator_username'),
    ]

    operations = [
        migrations.RunPython(
            drop_allauth_tables,
            reverse_drop_allauth_tables,
        ),
    ]
